### ISSUE TITLE
Smart distancing on Jetson nano has very low fps

### ISSUE THREAD

**Issue by grdsvt** [neuralet/neuralet#118] opened 2020-05-24 15:00 UTC
Hi, 
I solved the problem on my Jetson nano downgrade jetpack from 4.4 to 4.3 version and it is working,
but I see thet in the video it should have 17 - 20 fps (I read this in the blue text) but seeing the video I suppose that  fps is about 2-3, very slow.
How is it possible? Where is the problem?

Thanks

**Comment by mrn-mln** [comment] 2020-05-24 15:25
Hi @grdsvt,
Our video streaming method is a basic HTML method and this is why you see the output frame rate slower than the indicated fps in the blue text. The actual processing time is what the blue text indicates.
This issue will be solved at #87 #67

**Comment by wenzuolin-maker** [comment] 2020-05-29 07:15
Hi, I have a problem.
I want to open camera on nano using gstreamer. So I changed to "VideoPath: v4l2src device=/dev/video0 ! video/x-raw, width=640, height=480 ! 'videoconvert ! appsink" in config-jetson.ini file. This gstreamer pipline is working in python file.
And I changed "input_cap = cv.VideoCapture(video_uri, cv.CAP_GSTREAMER)" in libs/core.py.
but I saw "failed to load video ".
How can I solve it?

**Comment by mhejrati** [comment] 2020-06-03 04:48
@mhsekhavat

**Comment by codebugged** [comment] 2020-06-29 16:14
Hi @wenzuolin-maker 
Was your problem solved ?

If yes then please help me

**Comment by JsonSadler** [comment] 2020-07-07 13:52
> Hi, I have a problem.
> I want to open camera on nano using gstreamer. So I changed to "VideoPath: v4l2src device=/dev/video0 ! video/x-raw, width=640, height=480 ! 'videoconvert ! appsink" in config-jetson.ini file. This gstreamer pipline is working in python file.
> And I changed "input_cap = cv.VideoCapture(video_uri, cv.CAP_GSTREAMER)" in libs/core.py.
> but I saw "failed to load video ".
> How can I solve it?

more like it has been failed to load the default video sample as it has been removed, can you confirm the problem is with the VideoCapture for sure? 

@codebugged What was your problem exactly?

Some work has been done around to support gstreamer input, but not well tested and merged yet. See #70

**Closed as completed** 2022-12-12 20:37 UTC
